### ISSUE TITLE
Add palette of logic symbols

### ISSUE THREAD

**Issue by io12** [Bram-Hub/aris#65]
We already have macros for typing logic symbols (`forall` for ∀, `.bicon` for ↔, etc), but it might still be useful to have a container of buttons to insert logic symbols.

It's also an open question where this should be in the UI. Should it be a bootstrap popover from the text field? A collapsible menu on the top nav bar?

**Comment by Bram28** [comment]
I prefer a menu rather than a pop-up

Bram
