### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by io12** [Bram-Hub/aris#66]
It might be hard to figure this out, since many of the regular Java Aris shortcuts conflict with web browser shortcuts.

**Comment by io12** [comment]
Actually, it looks like it's possible for web apps to override web browser shortcuts. https://www.robin-drexler.com/2015/07/07/overriding-default-browser-shortcuts/

**Comment by Bram28** [comment]
Oooh, that might be nice!  Do you know the key shortcuts Fitch uses?

**Comment by io12** [comment]
Fixed with https://github.com/Bram-Hub/aris/commit/308c85bd30ca5ee576df388e65529314d2181176.
